'use strict';
const assert = require('assert');
const fs = require('fs');
const os = require('os');
const path = require('path');
let passed=0, failures=[]; function test(name,fn){try{fn();passed++;process.stdout.write(`  ✓ ${name}\n`)}catch(e){failures.push(e);process.stdout.write(`  ✗ ${name}\n    ${e.stack||e}\n`)}}
function task(){return {id:'edit-profile',title:'修改个人资料',goal:'更新昵称',entryPage:'profile',preconditions:['已登录'],risk:'local',status:'captured',steps:[{id:'open',instruction:'点击「编辑资料」',page:'profile',stateAfter:'open',action:{type:'click'}},{id:'save',instruction:'点击「保存修改」',page:'profile',risk:'write',action:{type:'click'}}],completion:{description:'个人中心显示更新后的内容',verification:'expected'},branches:[{id:'cooldown',condition:'教学信息处于冷却期',effect:'学科不可修改'}],relatedTasks:['view-benefits']}}
// 草稿会读取发布图计算 hash，因此夹具需要真实文件。
const PROJ=fs.mkdtempSync(path.join(os.tmpdir(),'manual-gen-task-'));process.on('exit',()=>fs.rmSync(PROJ,{recursive:true,force:true}));
fs.mkdirSync(path.join(PROJ,'docs/manual/images/annotated'),{recursive:true});fs.writeFileSync(path.join(PROJ,'docs/manual/images/annotated/edit-profile--open.png'),'png');
const CTX={projectRoot:PROJ,finalPath:path.join(PROJ,'docs/manual/tasks/edit-profile.md')};
function evidence(){return {steps:[{id:'open',status:'verified',screenshots:[{annotated:'docs/manual/images/annotated/edit-profile--open.png'}]},{id:'save',status:'not-executed',reason:'stop-before-action',screenshots:[]}]}}
process.stdout.write('\ngenerate task\n');
test('任务草稿包含规定章节且只引用 annotated 图片',()=>{const {buildTaskDraft}=require('../src/generate/task-draft');const r=buildTaskDraft(task(),evidence(),CTX);assert.strictEqual(r.ok,true,r.errors?.join('\n'));for(const h of ['# 修改个人资料','## 开始前','## 操作步骤','## 完成标志','## 条件分支','## 相关任务'])assert.ok(r.markdown.includes(h));assert.match(r.markdown,/images\/annotated/);assert.doesNotMatch(r.markdown,/artifacts\/raw|sanitized/);assert.match(r.markdown,/预期/)});
test('缺少关键截图或引用非 annotated 产物时阻止生成',()=>{const {buildTaskDraft}=require('../src/generate/task-draft');const bad=evidence();bad.steps[0].screenshots[0].annotated='.manual/artifacts/raw/x.png';const r=buildTaskDraft(task(),bad,CTX);assert.strictEqual(r.ok,false);assert.match(r.errors.join('\n'),/annotated/)});
test('结构化事实校验阻止调换步骤和虚报完成验证',()=>{const {buildTaskDraft}=require('../src/generate/task-draft');const {validateTaskFinal}=require('../src/generate/task-facts');const draft=buildTaskDraft(task(),evidence(),CTX);assert.strictEqual(validateTaskFinal(draft.markdown,draft.facts).ok,true);const reordered=draft.markdown.replace('<!-- step:open -->','<!-- step:temp -->').replace('<!-- step:save -->','<!-- step:open -->').replace('<!-- step:temp -->','<!-- step:save -->');assert.strictEqual(validateTaskFinal(reordered,draft.facts).ok,false);assert.strictEqual(validateTaskFinal(draft.markdown.replace('预期业务结果：','已验证界面结果：'),draft.facts).ok,false);assert.strictEqual(validateTaskFinal(draft.markdown.replace('预期业务结果：','已验证结果：'),draft.facts).ok,false)});
test('图片 href 相对正式文档位置，facts 分开记录 artifactPath 与 markdownHref',()=>{const {buildTaskDraft}=require('../src/generate/task-draft');const r=buildTaskDraft(task(),evidence(),CTX);assert.strictEqual(r.ok,true);assert.ok(r.markdown.includes('](../images/annotated/edit-profile--open.png)'));assert.ok(!r.markdown.includes('](docs/manual'));const {fileSha256}=require('../src/util/hash');assert.deepStrictEqual(r.facts.images,[{artifactPath:'docs/manual/images/annotated/edit-profile--open.png',markdownHref:'../images/annotated/edit-profile--open.png',sha256:fileSha256(path.join(PROJ,'docs/manual/images/annotated/edit-profile--open.png')),privacy:null}]);assert.strictEqual(buildTaskDraft(task(),evidence()).ok,false,'缺少文档位置时不能猜测 href')});
test('正式文档通过临时文件原子替换',()=>{const {publishAtomic}=require('../src/generate/task-draft');const root=fs.mkdtempSync(path.join(os.tmpdir(),'manual-publish-'));try{const file=path.join(root,'tasks','x.md');publishAtomic(file,'one');assert.strictEqual(fs.readFileSync(file,'utf8'),'one');assert.ok(!fs.existsSync(file+'.tmp'))}finally{fs.rmSync(root,{recursive:true,force:true})}});
test('公开模式只允许 annotated 图片',()=>{const {validatePublishedImages}=require('../src/privacy/publication');const config={privacy:{audience:'public'},artifacts:{annotatedDir:'docs/manual/images/annotated'}};assert.strictEqual(validatePublishedImages(['docs/manual/images/annotated/a.png'],config).ok,true);assert.strictEqual(validatePublishedImages([{artifactPath:'docs/manual/images/annotated/a.png',markdownHref:'../images/annotated/a.png'}],config).ok,true);assert.strictEqual(validatePublishedImages(['docs/manual/images/annotated/../raw/a.png'],config).ok,false);assert.strictEqual(validatePublishedImages(['.manual/artifacts/raw/a.png'],config).ok,false);assert.strictEqual(validatePublishedImages(['.manual/artifacts/sanitized/a.png'],config).ok,false);assert.strictEqual(validatePublishedImages(['.manual/artifacts/diagnostics/a.png'],config).ok,false)});
test('公开模式拒绝 blur 和未解决的高风险内容',()=>{const {validateEvidence}=require('../src/privacy/publication');const config={privacy:{audience:'public',maskStyle:'neutral-mosaic'},artifacts:{annotatedDir:'docs/manual/images/annotated'}};const blur={steps:[{screenshots:[{annotated:'docs/manual/images/annotated/a.png',redactions:[{result:'blur'}]}]}]};assert.strictEqual(validateEvidence(blur,config).ok,false);const unresolved={steps:[{screenshots:[{annotated:'docs/manual/images/annotated/a.png',unresolvedHighRisk:1,redactions:[]}]}]};assert.strictEqual(validateEvidence(unresolved,config).ok,false)});
test('发布事实摘要不包含敏感原文',()=>{const {summarizeEvidence}=require('../src/privacy/publication');const summary=summarizeEvidence({steps:[{screenshots:[{annotated:'docs/manual/images/annotated/a.png',redactions:[{kind:'phone',result:'neutral-mosaic'}]}]}]},{privacy:{audience:'public',maskStyle:'neutral-mosaic'}});assert.deepStrictEqual(summary,{audience:'public',maskStyles:['neutral-mosaic'],unresolvedHighRisk:0});assert.ok(!JSON.stringify(summary).includes('phone'))});
process.stdout.write(`\n${passed} passed, ${failures.length} failed\n`);if(failures.length)process.exitCode=1;
